# Generated by Django 5.2.17 on 2026-09-19 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('date_plein', models.DateField(verbose_name='date')),
                ('station', models.CharField(max_length=100, verbose_name='station')),
                ('quantite_litres', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='quantité (L)')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix unitaire (FCFA/L)')),
                ('km_compteur', models.PositiveIntegerField(verbose_name='km compteur')),
                ('numero_ticket', models.CharField(max_length=50, verbose_name='n° ticket / reçu')),
                ('km_precedent', models.PositiveIntegerField(blank=True, null=True, verbose_name='km du plein précédent')),
                ('distance_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='distance depuis le plein précédent')),
                ('consommation', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='consommation (L/100 km)')),
                ('moyenne_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='moyenne des pleins précédents (L/100 km)')),
                ('ecart_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='écart à la moyenne (%)')),
                ('niveau_alerte', models.CharField(choices=[('AUCUNE', 'Aucune'), ('JAUNE', 'Jaune (> +20 %)'), ('ROUGE', 'Rouge (> +40 %)')], default='AUCUNE', max_length=6, verbose_name='alerte')),
                ('alerte_saisie', models.BooleanField(default=False, verbose_name='alerte de saisie (écart > ±60 %)')),
                ('anomalie', models.BooleanField(default=False, verbose_name='anomalie (> 45 ou < 20 L/100 km)')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pleins', to='drivers.chauffeur', verbose_name='chauffeur')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pleins', to='fleet.vehicule', verbose_name='camion')),
            ],
            options={
                'verbose_name': 'plein',
                'verbose_name_plural': 'pleins',
                'ordering': ['-date_plein', '-pk'],
                'indexes': [models.Index(fields=['vehicule', 'date_plein'], name='fuel_plein_vehicul_5a3f4d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantite_litres__gt', 0)), name='plein_quantite_positive'), models.CheckConstraint(condition=models.Q(('prix_unitaire__gt', 0)), name='plein_prix_positif'), models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('numero_ticket',), name='plein_ticket_unique')],
            },
        ),
    ]
