# Generated by Django 5.2.17 on 2026-09-19 11:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='raison sociale')),
                ('ncc_nif', models.CharField(max_length=50, unique=True, verbose_name='NCC / NIF')),
                ('contact_principal', models.CharField(max_length=150, verbose_name='contact principal')),
                ('telephone', models.CharField(max_length=20, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('adresse', models.TextField(verbose_name='adresse / siège')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='taux de TVA (%)')),
                ('motif_exoneration', models.CharField(blank=True, choices=[('EXPORT', 'Export'), ('ONG', 'ONG'), ('CONVENTION', 'Convention'), ('AUTRE', 'Autre')], max_length=12, verbose_name="motif d'exonération")),
                ('charge_clientele', models.ForeignKey(blank=True, limit_choices_to={'role': 'CHARGE_CLIENTELE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='chargé clientèle attitré')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('type_interaction', models.CharField(choices=[('APPEL', 'Appel'), ('MAIL', 'Mail'), ('REUNION', 'Réunion'), ('DEMANDE_DEVIS', 'Demande de devis'), ('RECLAMATION', 'Réclamation')], max_length=15, verbose_name='type')),
                ('date_interaction', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('resume', models.TextField(verbose_name="résumé / notes d'échange")),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='customers.client', verbose_name='client')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'interaction',
                'verbose_name_plural': 'interactions',
                'ordering': ['-date_interaction'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['raison_sociale'], name='customers_c_raison__77c7b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(('taux_tva__gt', 0), models.Q(('motif_exoneration', ''), _negated=True), _connector='OR'), name='client_tva_zero_requiert_motif'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(('taux_tva__gte', 0), ('taux_tva__lte', 100)), name='client_taux_tva_entre_0_et_100'),
        ),
    ]
