# Generated by Django 5.2.17 on 2026-09-19 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='delai_paiement_jours',
            field=models.PositiveSmallIntegerField(default=30, help_text="Date d'échéance de ses factures = date d'émission + ce délai.", verbose_name='délai de paiement (jours)'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(('delai_paiement_jours__gte', 1), ('delai_paiement_jours__lte', 365)), name='client_delai_paiement_entre_1_et_365'),
        ),
    ]
