# Generated by Django 5.2.17 on 2026-09-21 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppareilMFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64, verbose_name='secret TOTP')),
                ('confirme', models.BooleanField(default=False, verbose_name='confirmé')),
                ('dernier_pas', models.BigIntegerField(default=0, verbose_name='dernier intervalle accepté')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('confirme_le', models.DateTimeField(blank=True, null=True, verbose_name='confirmé le')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appareil_mfa', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'appareil MFA',
                'verbose_name_plural': 'appareils MFA',
                'db_table': 'accounts_appareil_mfa',
            },
        ),
        migrations.CreateModel(
            name='CodeSecours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empreinte', models.CharField(db_index=True, max_length=64, verbose_name='empreinte SHA-256')),
                ('utilise_le', models.DateTimeField(blank=True, null=True, verbose_name='utilisé le')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_secours', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'code de secours',
                'verbose_name_plural': 'codes de secours',
                'db_table': 'accounts_code_secours',
            },
        ),
    ]
