# Generated by Django 5.2.17 on 2026-09-19 12:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreReparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='numéro')),
                ('type_or', models.CharField(choices=[('CURATIF', 'Curatif'), ('PREVENTIF', 'Préventif'), ('DIAGNOSTIC', 'Diagnostic'), ('PNEUMATIQUES', 'Pneumatiques')], max_length=15, verbose_name='type')),
                ('lieu', models.CharField(choices=[('INTERNE', 'Garage interne DEN Source'), ('EXTERNE', 'Prestataire externe')], max_length=10, verbose_name='lieu')),
                ('motif', models.TextField(verbose_name='motif / symptômes')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('CLOTURE', 'Clôturé')], default='OUVERT', max_length=10, verbose_name='statut')),
                ('date_ouverture', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ouvert le')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='clôturé le')),
                ('cout_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="coût de la main-d'œuvre (FCFA)")),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordres_reparation', to='fleet.vehicule', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'ordre de réparation',
                'verbose_name_plural': 'ordres de réparation',
                'ordering': ['-numero'],
                'indexes': [models.Index(fields=['vehicule', 'statut'], name='garage_ordr_vehicul_bdbad2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('statut', 'OUVERT'), ('date_cloture__isnull', False), _connector='OR'), name='or_cloture_requiert_date'), models.CheckConstraint(condition=models.Q(('cout_main_oeuvre__gte', 0)), name='or_cout_main_oeuvre_positif_ou_nul')],
            },
        ),
    ]
