# Generated by Django 5.2.17 on 2026-09-19 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
        ('garage', '0001_initial'),
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('points', models.JSONField(default=list, verbose_name='points contrôlés')),
                ('nb_anomalies', models.PositiveSmallIntegerField(default=0, verbose_name='points KO')),
                ('remarque', models.TextField(blank=True, verbose_name='remarque générale')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='drivers.chauffeur', verbose_name='chauffeur')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='missions.mission', verbose_name='mission')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='fleet.vehicule', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'check-list véhicule',
                'verbose_name_plural': 'check-lists véhicule',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('mission',), name='checklist_une_par_mission')],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('type_incident', models.CharField(choices=[('PANNE', 'Panne'), ('ACCIDENT', 'Accident'), ('AUTRE', 'Autre')], max_length=10, verbose_name='type')),
                ('gravite', models.CharField(choices=[('FAIBLE', 'Faible : le camion peut rouler'), ('MOYENNE', 'Moyenne : intervention nécessaire'), ('GRAVE', 'Grave : camion immobilisé')], max_length=10, verbose_name='gravité')),
                ('description', models.TextField(verbose_name='description')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='lieu')),
                ('statut', models.CharField(choices=[('SIGNALE', 'Signalé'), ('PRIS_EN_COMPTE', 'Pris en compte'), ('CLOS', 'Clos')], default='SIGNALE', max_length=15, verbose_name='statut')),
                ('note_traitement', models.TextField(blank=True, verbose_name='suite donnée')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('chauffeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='drivers.chauffeur', verbose_name='chauffeur')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='missions.mission', verbose_name='mission')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='fleet.vehicule', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'incident',
                'verbose_name_plural': 'incidents',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['statut', 'gravite'], name='garage_inci_statut_96b6d8_idx')],
            },
        ),
    ]
