# Generated by Django 5.2.17 on 2026-09-19 16:13

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_delai_paiement'),
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='numéro')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('A_VALIDER', 'À valider'), ('EMISE', 'Émise'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('PAYEE', 'Payée')], default='BROUILLON', max_length=20, verbose_name='statut')),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='taux de TVA (%)')),
                ('motif_exoneration', models.CharField(blank=True, choices=[('EXPORT', 'Export'), ('ONG', 'ONG'), ('CONVENTION', 'Convention'), ('AUTRE', 'Autre')], max_length=12, verbose_name="motif d'exonération")),
                ('delai_paiement_jours', models.PositiveSmallIntegerField(verbose_name='délai de paiement (jours)')),
                ('date_emission', models.DateField(blank=True, null=True, verbose_name="date d'émission")),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="date d'échéance")),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total HT (FCFA)')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA (FCFA)')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total TTC (FCFA)')),
                ('motif_refus', models.TextField(blank=True, verbose_name='motif du dernier refus')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='validée le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='customers.client', verbose_name='client')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='préparée par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='missions.mission', verbose_name='mission')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validée par')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'ordering': ['-date_emission', '-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('designation', models.CharField(max_length=255, verbose_name='désignation')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='prix unitaire HT (FCFA)')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant HT (FCFA)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='billing.facture', verbose_name='facture')),
            ],
            options={
                'verbose_name': 'ligne de facture',
                'verbose_name_plural': 'lignes de facture',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('date_reglement', models.DateField(verbose_name='date du règlement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant (FCFA)')),
                ('mode', models.CharField(choices=[('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('ESPECES', 'Espèces'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MONEY', 'MTN Mobile Money')], max_length=14, verbose_name='mode de paiement')),
                ('reference', models.CharField(blank=True, help_text='N° de chèque, de virement ou de transaction.', max_length=100, verbose_name='référence')),
                ('motif_annulation', models.TextField(blank=True, verbose_name="motif d'annulation")),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='billing.facture', verbose_name='facture')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'règlement',
                'verbose_name_plural': 'règlements',
                'ordering': ['-date_reglement', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('categorie', models.CharField(choices=[('PEAGES', 'Péages'), ('ENTRETIEN', 'Entretien'), ('FRAIS_ADMIN', 'Frais administratifs'), ('AUTRE', 'Autre')], max_length=12, verbose_name='catégorie')),
                ('date_depense', models.DateField(verbose_name='date')),
                ('libelle', models.CharField(max_length=200, verbose_name='libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant (FCFA)')),
                ('mode', models.CharField(choices=[('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('ESPECES', 'Espèces'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MONEY', 'MTN Mobile Money')], max_length=14, verbose_name='mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='n° de pièce')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='missions.mission', verbose_name='mission')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dépense',
                'verbose_name_plural': 'dépenses',
                'ordering': ['-date_depense', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='depense_montant_positif')],
            },
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['statut', 'date_echeance'], name='billing_fac_statut_cd28dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.UniqueConstraint(condition=models.Q(('numero', ''), _negated=True), fields=('numero',), name='facture_numero_unique'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('mission',), name='facture_une_par_mission'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('taux_tva__gt', 0), models.Q(('motif_exoneration', ''), _negated=True), _connector='OR'), name='facture_tva_zero_requiert_motif'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('taux_tva__gte', 0), ('taux_tva__lte', 100)), name='facture_taux_tva_entre_0_et_100'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('montant_ttc', django.db.models.expressions.CombinedExpression(models.F('montant_ht'), '+', models.F('montant_tva')))), name='facture_ttc_egal_ht_plus_tva'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('statut__in', ['BROUILLON', 'A_VALIDER']), models.Q(models.Q(('numero', ''), _negated=True), ('date_emission__isnull', False), ('date_echeance__isnull', False)), _connector='OR'), name='facture_emise_a_numero_et_dates'),
        ),
        migrations.AddConstraint(
            model_name='lignefacture',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='ligne_facture_quantite_positive'),
        ),
        migrations.AddConstraint(
            model_name='lignefacture',
            constraint=models.CheckConstraint(condition=models.Q(('prix_unitaire_ht__gte', 0)), name='ligne_facture_prix_positif'),
        ),
        migrations.AddConstraint(
            model_name='reglement',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='reglement_montant_positif'),
        ),
    ]
