# Generated by Django 5.2.17 on 2026-09-24 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='origine',
            field=models.CharField(blank=True, choices=[('PLEIN', 'Plein de carburant'), ('ACHAT_STOCK', 'Achat de pièces'), ('MAIN_OEUVRE_OR', "Main-d'œuvre d'un OR")], help_text='Renseignée pour une dépense créée automatiquement (plein, achat de pièces, OR).', max_length=14, verbose_name='origine'),
        ),
        migrations.AddField(
            model_name='depense',
            name='origine_id',
            field=models.PositiveBigIntegerField(blank=True, help_text="Numéro du plein, du mouvement de stock ou de l'OR à l'origine de la dépense.", null=True, verbose_name="identifiant de l'origine"),
        ),
        migrations.AlterField(
            model_name='depense',
            name='categorie',
            field=models.CharField(choices=[('PEAGES', 'Péages'), ('ENTRETIEN', 'Entretien'), ('FRAIS_ADMIN', 'Frais administratifs'), ('AUTRE', 'Autre'), ('CARBURANT', 'Carburant'), ('PIECES', 'Pièces détachées'), ('MAINTENANCE', "Main-d'œuvre des réparations")], max_length=12, verbose_name='catégorie'),
        ),
        migrations.AddConstraint(
            model_name='depense',
            constraint=models.UniqueConstraint(condition=models.Q(('origine', ''), _negated=True), fields=('origine', 'origine_id'), name='depense_une_par_origine'),
        ),
    ]
