# Generated by Django 5.2.17 on 2026-09-26 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_depenses_automatiques_parc_auto'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='vehicule',
            field=models.ForeignKey(blank=True, help_text="Renseigné pour un plein, une main-d'œuvre d'OR ou un ordre de décaissement lié à un camion.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='fleet.vehicule', verbose_name='camion'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='categorie',
            field=models.CharField(choices=[('PEAGES', 'Péages'), ('ENTRETIEN', 'Entretien'), ('FRAIS_ADMIN', 'Frais administratifs'), ('AUTRE', 'Autre'), ('CARBURANT', 'Carburant'), ('PIECES', 'Pièces détachées'), ('MAINTENANCE', "Main-d'œuvre des réparations"), ('FRAIS_MISSION', 'Frais de mission (avance, imprévu)')], max_length=14, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='origine',
            field=models.CharField(blank=True, choices=[('PLEIN', 'Plein de carburant'), ('ACHAT_STOCK', 'Achat de pièces'), ('MAIN_OEUVRE_OR', "Main-d'œuvre d'un OR"), ('FRAIS_MISSION', 'Frais de mission confirmé'), ('ORDRE_DECAISSEMENT', 'Ordre de décaissement exécuté')], help_text='Renseignée pour une dépense créée automatiquement (plein, achat de pièces, OR).', max_length=20, verbose_name='origine'),
        ),
    ]
