# Generated by Django 5.2.17 on 2026-09-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_reprise_depenses_parc_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='categorie',
            field=models.CharField(choices=[('PEAGES', 'Péages'), ('ENTRETIEN', 'Entretien'), ('FRAIS_ADMIN', 'Frais administratifs'), ('AUTRE', 'Autre'), ('CARBURANT', 'Carburant'), ('PIECES', 'Pièces détachées'), ('MAINTENANCE', "Main-d'œuvre des réparations"), ('FRAIS_MISSION', 'Frais de mission (avance, imprévu)')], max_length=14, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='origine',
            field=models.CharField(blank=True, choices=[('PLEIN', 'Plein de carburant'), ('ACHAT_STOCK', 'Achat de pièces'), ('MAIN_OEUVRE_OR', "Main-d'œuvre d'un OR"), ('FRAIS_MISSION', 'Frais de mission confirmé')], help_text='Renseignée pour une dépense créée automatiquement (plein, achat de pièces, OR).', max_length=14, verbose_name='origine'),
        ),
    ]
