# Generated by Django 5.2.17 on 2026-09-26 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_depenses_automatiques_parc_auto'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='vehicule',
            field=models.ForeignKey(blank=True, help_text="Renseigné pour un plein, une main-d'œuvre d'OR ou un ordre de décaissement lié à un camion.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='fleet.vehicule', verbose_name='camion'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='origine',
            field=models.CharField(blank=True, choices=[('PLEIN', 'Plein de carburant'), ('ACHAT_STOCK', 'Achat de pièces'), ('MAIN_OEUVRE_OR', "Main-d'œuvre d'un OR"), ('ORDRE_DECAISSEMENT', 'Ordre de décaissement exécuté')], help_text='Renseignée pour une dépense créée automatiquement (plein, achat de pièces, OR).', max_length=20, verbose_name='origine'),
        ),
    ]
