# Generated by Django 5.2.17 on 2026-09-26 01:39

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_depense_vehicule_alter_depense_categorie_and_more'),
        ('customers', '0002_delai_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='numéro')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('CONTRE_PROPOSEE', 'Contre-proposée'), ('EN_ATTENTE_DIRECTION', 'En attente de la direction'), ('VALIDEE', 'Validée'), ('ENVOYEE_CLIENT', 'Envoyée au client'), ('ACCEPTEE', 'Acceptée par le client'), ('REFUSEE', 'Refusée par le client'), ('EXPIREE', 'Expirée'), ('CONVERTIE', 'Convertie en mission')], default='BROUILLON', max_length=20, verbose_name='statut')),
                ('lieu_chargement', models.CharField(max_length=200, verbose_name='lieu de chargement')),
                ('lieu_livraison', models.CharField(max_length=200, verbose_name='lieu de livraison')),
                ('nature_marchandise', models.CharField(max_length=200, verbose_name='nature de la marchandise')),
                ('poids_t', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='poids (t)')),
                ('date_depart_souhaitee', models.DateField(blank=True, null=True, verbose_name='départ souhaité')),
                ('prix_convenu', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='prix convenu HT (FCFA)')),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='taux de TVA (%)')),
                ('motif_exoneration', models.CharField(blank=True, choices=[('EXPORT', 'Export'), ('ONG', 'ONG'), ('CONVENTION', 'Convention'), ('AUTRE', 'Autre')], max_length=12, verbose_name="motif d'exonération")),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total HT (FCFA)')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA (FCFA)')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total TTC (FCFA)')),
                ('motif_contre_proposition', models.TextField(blank=True, verbose_name='motif de la dernière contre-proposition')),
                ('motif_refus_client', models.TextField(blank=True, verbose_name='motif du refus du client')),
                ('date_envoi', models.DateField(blank=True, null=True, verbose_name='envoyée au client le')),
                ('date_validite', models.DateField(blank=True, null=True, verbose_name="valable jusqu'au")),
                ('date_validation_finances', models.DateTimeField(blank=True, null=True, verbose_name='validé par la finance le')),
                ('date_validation_direction', models.DateTimeField(blank=True, null=True, verbose_name='validé par la direction le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proformas', to='customers.client', verbose_name='client')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='préparé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('valide_par_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validé par la direction')),
                ('valide_par_finances', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validé par la finance')),
            ],
            options={
                'verbose_name': 'devis',
                'verbose_name_plural': 'devis',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['statut', 'date_validite'], name='billing_pro_statut_8948b7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('numero', ''), _negated=True), fields=('numero',), name='proforma_numero_unique'), models.CheckConstraint(condition=models.Q(('poids_t__gt', 0)), name='proforma_poids_positif'), models.CheckConstraint(condition=models.Q(('prix_convenu__gte', 0)), name='proforma_prix_positif_ou_nul'), models.CheckConstraint(condition=models.Q(('taux_tva__gt', 0), models.Q(('motif_exoneration', ''), _negated=True), _connector='OR'), name='proforma_tva_zero_requiert_motif'), models.CheckConstraint(condition=models.Q(('taux_tva__gte', 0), ('taux_tva__lte', 100)), name='proforma_taux_tva_entre_0_et_100'), models.CheckConstraint(condition=models.Q(('montant_ttc', django.db.models.expressions.CombinedExpression(models.F('montant_ht'), '+', models.F('montant_tva')))), name='proforma_ttc_egal_ht_plus_tva')],
            },
        ),
    ]
