# Generated by Django 5.2.17 on 2026-09-28 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_proforma'),
        ('fleet', '0001_initial'),
        ('missions', '0004_mission_copilote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Part de TVA incluse dans le montant, si le fournisseur l'a facturée et que la pièce le justifie. Laisser à 0 si aucune TVA récupérable (fournisseur informel, non assujetti…).", max_digits=14, verbose_name='dont TVA déductible (FCFA)'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant TTC (FCFA)'),
        ),
        migrations.AddConstraint(
            model_name='depense',
            constraint=models.CheckConstraint(condition=models.Q(('montant_tva__gte', 0)), name='depense_montant_tva_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='depense',
            constraint=models.CheckConstraint(condition=models.Q(('montant_tva__lt', models.F('montant'))), name='depense_montant_tva_inferieur_au_montant'),
        ),
    ]
