# Generated by Django 5.2.17 on 2026-09-19 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementManuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('sens', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=6, verbose_name='sens')),
                ('date_mouvement', models.DateField(verbose_name='date')),
                ('libelle', models.CharField(max_length=200, verbose_name='libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant (FCFA)')),
                ('mode', models.CharField(choices=[('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('ESPECES', 'Espèces'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MONEY', 'MTN Mobile Money')], max_length=14, verbose_name='mode')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('motif_annulation', models.TextField(blank=True, verbose_name="motif d'annulation")),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mouvement de trésorerie',
                'verbose_name_plural': 'mouvements de trésorerie',
                'ordering': ['-date_mouvement', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='mouvement_montant_positif')],
            },
        ),
    ]
