# Generated by Django 5.2.17 on 2026-09-26 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_depense_vehicule_alter_depense_origine'),
        ('finance', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='numéro')),
                ('categorie', models.CharField(choices=[('PEAGES', 'Péages'), ('ENTRETIEN', 'Entretien'), ('FRAIS_ADMIN', 'Frais administratifs'), ('AUTRE', 'Autre'), ('CARBURANT', 'Carburant'), ('PIECES', 'Pièces détachées'), ('MAINTENANCE', "Main-d'œuvre des réparations")], max_length=12, verbose_name='catégorie')),
                ('origine', models.CharField(choices=[('MANUELLE', 'Demande du Parc Auto'), ('DEPASSEMENT_ENVELOPPE', "Dépassement d'enveloppe")], max_length=21, verbose_name='origine')),
                ('montant_estime', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant estimé (FCFA)')),
                ('motif', models.TextField(verbose_name='motif')),
                ('fournisseur', models.CharField(blank=True, max_length=200, verbose_name='fournisseur')),
                ('piece_jointe', models.FileField(blank=True, help_text='Devis du fournisseur, par exemple.', upload_to='demandes_depense/%Y/%m/', verbose_name='pièce jointe')),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='SOUMISE', max_length=10, verbose_name='statut')),
                ('date_decision', models.DateTimeField(blank=True, null=True, verbose_name='décidée le')),
                ('motif_refus', models.TextField(blank=True, verbose_name='motif du refus')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='demandeur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='décidée par')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_depense', to='fleet.vehicule', verbose_name='camion')),
            ],
            options={
                'verbose_name': 'demande de dépense',
                'verbose_name_plural': 'demandes de dépense',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EnveloppeDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('categorie', models.CharField(choices=[('PEAGES', 'Péages'), ('ENTRETIEN', 'Entretien'), ('FRAIS_ADMIN', 'Frais administratifs'), ('AUTRE', 'Autre'), ('CARBURANT', 'Carburant'), ('PIECES', 'Pièces détachées'), ('MAINTENANCE', "Main-d'œuvre des réparations")], max_length=12, verbose_name='catégorie')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='année')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='mois')),
                ('montant_plafond', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='plafond (FCFA)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='approuvée par')),
                ('vehicule', models.ForeignKey(blank=True, help_text='Vide : enveloppe globale pour cette catégorie, tous camions confondus.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enveloppes_depense', to='fleet.vehicule', verbose_name='camion')),
            ],
            options={
                'verbose_name': 'enveloppe de dépense',
                'verbose_name_plural': 'enveloppes de dépense',
                'ordering': ['-annee', '-mois', 'categorie'],
            },
        ),
        migrations.CreateModel(
            name='OrdreDecaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='numéro')),
                ('montant_valide', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant validé (FCFA)')),
                ('statut', models.CharField(choices=[('A_EXECUTER', 'À exécuter'), ('EN_ATTENTE_REVALIDATION', 'En attente de revalidation'), ('EXECUTE', 'Exécuté')], default='A_EXECUTER', max_length=23, verbose_name='statut')),
                ('mode_paiement', models.CharField(blank=True, choices=[('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('ESPECES', 'Espèces'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MONEY', 'MTN Mobile Money')], max_length=14, verbose_name='mode de paiement')),
                ('justificatif', models.FileField(blank=True, upload_to='ordres_decaissement/%Y/%m/', verbose_name='justificatif')),
                ('montant_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='montant réel (FCFA)')),
                ('date_execution', models.DateTimeField(blank=True, null=True, verbose_name='exécuté le')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ordre_decaissement', to='finance.demandedepense', verbose_name='demande')),
                ('depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.depense', verbose_name='dépense')),
                ('execute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='exécuté par')),
            ],
            options={
                'verbose_name': 'ordre de décaissement',
                'verbose_name_plural': 'ordres de décaissement',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='demandedepense',
            index=models.Index(fields=['categorie', 'vehicule', 'statut'], name='finance_dem_categor_2d1b28_idx'),
        ),
        migrations.AddConstraint(
            model_name='demandedepense',
            constraint=models.CheckConstraint(condition=models.Q(('montant_estime__gt', 0)), name='demande_depense_montant_positif'),
        ),
        migrations.AddConstraint(
            model_name='enveloppedepense',
            constraint=models.UniqueConstraint(fields=('categorie', 'vehicule', 'annee', 'mois'), name='enveloppe_unique_par_scope_et_mois'),
        ),
        migrations.AddConstraint(
            model_name='enveloppedepense',
            constraint=models.CheckConstraint(condition=models.Q(('montant_plafond__gt', 0)), name='enveloppe_plafond_positif'),
        ),
        migrations.AddConstraint(
            model_name='enveloppedepense',
            constraint=models.CheckConstraint(condition=models.Q(('mois__gte', 1), ('mois__lte', 12)), name='enveloppe_mois_valide'),
        ),
        migrations.AddConstraint(
            model_name='ordredecaissement',
            constraint=models.CheckConstraint(condition=models.Q(('montant_valide__gt', 0)), name='ordre_decaissement_montant_positif'),
        ),
    ]
