# Generated by Django 5.2.17 on 2026-09-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_demandedepense_enveloppedepense_ordredecaissement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementmanuel',
            name='nature',
            field=models.CharField(choices=[('SOLDE_OUVERTURE', "Solde d'ouverture"), ('APPORT', "Apport de l'exploitant"), ('RETRAIT', "Retrait de l'exploitant"), ('FRAIS_BANCAIRE', 'Frais bancaires'), ('AUTRE', 'Autre')], default='AUTRE', max_length=16, verbose_name='nature'),
        ),
    ]
