# Generated by Django 5.2.17 on 2026-09-28 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_mouvementmanuel_nature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneReleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('date_operation', models.DateField(verbose_name='date')),
                ('libelle', models.CharField(max_length=200, verbose_name='libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant (FCFA)')),
                ('sens', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=6, verbose_name='sens')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('pointee', models.BooleanField(default=False, verbose_name='pointée')),
                ('mouvement_origine', models.CharField(blank=True, help_text='REGLEMENT, DEPENSE ou MANUEL — renseignée une fois la ligne pointée.', max_length=10, verbose_name='origine du mouvement rapproché')),
                ('mouvement_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='identifiant du mouvement rapproché')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ligne de relevé bancaire',
                'verbose_name_plural': 'lignes de relevé bancaire',
                'ordering': ['-date_operation', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='ligne_releve_montant_positif')],
            },
        ),
    ]
