# Generated by Django 5.2.17 on 2026-09-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteurNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixe', models.CharField(max_length=10, verbose_name='préfixe')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='année')),
                ('dernier', models.PositiveIntegerField(default=0, verbose_name='dernier numéro attribué')),
            ],
            options={
                'verbose_name': 'compteur de numéros',
                'verbose_name_plural': 'compteurs de numéros',
                'constraints': [models.UniqueConstraint(fields=('prefixe', 'annee'), name='compteur_numero_unique')],
            },
        ),
    ]
