# Generated by Django 5.2.17 on 2026-09-26 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='numéro')),
                ('libelle', models.CharField(max_length=150, verbose_name='libellé')),
                ('nature', models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif'), ('CHARGE', 'Charge'), ('PRODUIT', 'Produit')], max_length=10, verbose_name='nature')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'compte',
                'verbose_name_plural': 'plan comptable',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='numéro')),
                ('journal', models.CharField(choices=[('ACH', 'Achats'), ('VTE', 'Ventes'), ('BQ', 'Banque'), ('CAI', 'Caisse'), ('OD', 'Opérations diverses')], max_length=3, verbose_name='journal')),
                ('date_ecriture', models.DateField(verbose_name='date')),
                ('libelle', models.CharField(max_length=255, verbose_name='libellé')),
                ('piece_reference', models.CharField(blank=True, max_length=30, verbose_name='pièce justificative')),
                ('origine', models.CharField(blank=True, max_length=30, verbose_name='origine')),
                ('origine_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID origine')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée')], default='VALIDEE', max_length=10, verbose_name='statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='validée le')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validée par')),
            ],
            options={
                'verbose_name': 'écriture comptable',
                'verbose_name_plural': 'écritures comptables',
                'ordering': ['-date_ecriture', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(choices=[('DEBIT', 'Débit'), ('CREDIT', 'Crédit')], max_length=6, verbose_name='sens')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant (FCFA)')),
                ('libelle', models.CharField(blank=True, max_length=255, verbose_name='libellé')),
                ('tiers_type', models.CharField(blank=True, max_length=20, verbose_name='type de tiers')),
                ('tiers_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID tiers')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='accounting.compte', verbose_name='compte')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='accounting.ecriturecomptable', verbose_name='écriture')),
            ],
            options={
                'verbose_name': "ligne d'écriture",
                'verbose_name_plural': "lignes d'écriture",
                'ordering': ['ecriture', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['journal', 'date_ecriture'], name='accounting__journal_a1dd27_idx'),
        ),
        migrations.AddConstraint(
            model_name='ecriturecomptable',
            constraint=models.UniqueConstraint(condition=models.Q(('numero', ''), _negated=True), fields=('numero',), name='ecriture_numero_unique'),
        ),
        migrations.AddConstraint(
            model_name='ecriturecomptable',
            constraint=models.UniqueConstraint(condition=models.Q(('origine', ''), _negated=True), fields=('origine', 'origine_id'), name='ecriture_une_par_origine'),
        ),
        migrations.AddIndex(
            model_name='ligneecriture',
            index=models.Index(fields=['compte'], name='accounting__compte__6c10c8_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneecriture',
            index=models.Index(fields=['tiers_type', 'tiers_id'], name='accounting__tiers_t_c5e0bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='ligneecriture',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='ligne_ecriture_montant_positif'),
        ),
    ]
