# Generated by Django 5.2.17 on 2026-09-27 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_plan_comptable_seed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('annee', models.PositiveSmallIntegerField(unique=True, verbose_name='année')),
                ('date_debut', models.DateField(verbose_name='début')),
                ('date_fin', models.DateField(verbose_name='fin')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('CLOTURE', 'Clôturé')], default='OUVERT', max_length=10, verbose_name='statut')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='clôturé le')),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='clôturé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'exercice comptable',
                'verbose_name_plural': 'exercices comptables',
                'ordering': ['-annee'],
            },
        ),
    ]
