# Generated by Django 5.2.17 on 2026-09-19 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='référence')),
                ('designation', models.CharField(max_length=200, verbose_name='désignation')),
                ('categorie', models.CharField(blank=True, max_length=100, verbose_name='catégorie')),
                ('emplacement', models.CharField(blank=True, max_length=100, verbose_name='emplacement')),
                ('quantite', models.PositiveIntegerField(default=0, verbose_name='quantité en stock')),
                ('seuil_minimal', models.PositiveIntegerField(default=0, help_text="0 = pas d'alerte de seuil pour cet article.", verbose_name='seuil minimal')),
                ('pump', models.DecimalField(decimal_places=2, default=0, help_text='Prix unitaire moyen pondéré.', max_digits=12, verbose_name='PUMP (FCFA)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée (achat)'), ('SORTIE', 'Sortie (liée à un OR)'), ('AJUSTEMENT', 'Ajustement')], max_length=12, verbose_name='type')),
                ('variation', models.IntegerField(help_text='Positive en entrée, négative en sortie.', verbose_name='variation')),
                ('quantite_apres', models.PositiveIntegerField(verbose_name='stock après mouvement')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text="Prix d'achat en entrée ; PUMP au moment du mouvement sinon.", max_digits=12, verbose_name='prix unitaire (FCFA)')),
                ('motif', models.TextField(blank=True, verbose_name='motif')),
                ('date_mouvement', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date')),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='acteur')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='inventory.article', verbose_name='article')),
                ('ordre_reparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='garage.ordrereparation', verbose_name='ordre de réparation')),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'ordering': ['-date_mouvement', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['designation'], name='inventory_a_designa_081e6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_mouvement', 'ENTREE'), _negated=True), ('variation__gt', 0), _connector='OR'), name='mouvement_entree_variation_positive'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_mouvement', 'SORTIE'), _negated=True), ('variation__lt', 0), _connector='OR'), name='mouvement_sortie_variation_negative'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_mouvement', 'AJUSTEMENT'), _negated=True), models.Q(('variation', 0), _negated=True), _connector='OR'), name='mouvement_ajustement_non_nul'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_mouvement', 'SORTIE'), _negated=True), ('ordre_reparation__isnull', False), _connector='OR'), name='mouvement_sortie_requiert_or'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_mouvement', 'ENTREE'), _negated=True), ('ordre_reparation__isnull', True), _connector='OR'), name='mouvement_entree_sans_or'),
        ),
    ]
