# Generated by Django 5.2.17 on 2026-09-19 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='numéro')),
                ('lieu_chargement', models.CharField(max_length=200, verbose_name='lieu de chargement')),
                ('lieu_livraison', models.CharField(max_length=200, verbose_name='lieu de livraison')),
                ('nature_marchandise', models.CharField(max_length=200, verbose_name='nature de la marchandise')),
                ('poids_t', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='poids (t)')),
                ('prix_convenu', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='prix convenu (FCFA)')),
                ('date_depart_prevue', models.DateField(blank=True, help_text="Nécessaire à l'alerte N1 « chauffeur avec mission sur la période » des congés (cahier-des-charges.md:219-221).", null=True, verbose_name='départ prévu')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PLANIFIEE', 'Planifiée'), ('AFFECTEE', 'Affectée'), ('EN_COURS_DEPART', 'En cours : départ'), ('EN_COURS_COLIS_RECUPERE', 'En cours : colis récupéré'), ('LIVREE', 'Livrée'), ('CLOTUREE', 'Clôturée et validée')], default='BROUILLON', max_length=25, verbose_name='statut')),
                ('code_expediteur', models.CharField(max_length=12, verbose_name='code expéditeur')),
                ('code_destinataire', models.CharField(max_length=12, verbose_name='code destinataire')),
                ('km_depart', models.PositiveIntegerField(blank=True, null=True, verbose_name='km au départ')),
                ('km_arrivee', models.PositiveIntegerField(blank=True, null=True, verbose_name="km à l'arrivée")),
                ('date_depart', models.DateTimeField(blank=True, null=True, verbose_name='départ effectif')),
                ('date_recuperation', models.DateTimeField(blank=True, null=True, verbose_name='colis récupéré le')),
                ('date_livraison', models.DateTimeField(blank=True, null=True, verbose_name='livrée le')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='clôturée le')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='drivers.chauffeur', verbose_name='chauffeur')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='customers.client', verbose_name='client')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='fleet.vehicule', verbose_name='camion')),
            ],
            options={
                'verbose_name': 'mission',
                'verbose_name_plural': 'missions',
                'ordering': ['-numero'],
                'indexes': [models.Index(fields=['statut'], name='missions_mi_statut_25d39c_idx'), models.Index(fields=['vehicule', 'statut'], name='missions_mi_vehicul_f7bdb6_idx'), models.Index(fields=['chauffeur', 'statut'], name='missions_mi_chauffe_cc3387_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('statut__in', ['BROUILLON', 'PLANIFIEE']), models.Q(('vehicule__isnull', False), ('chauffeur__isnull', False)), _connector='OR'), name='mission_affectee_requiert_camion_et_chauffeur'), models.CheckConstraint(condition=models.Q(('poids_t__gt', 0)), name='mission_poids_positif'), models.CheckConstraint(condition=models.Q(('prix_convenu__gte', 0)), name='mission_prix_positif_ou_nul'), models.CheckConstraint(condition=models.Q(('km_arrivee__isnull', True), ('km_depart__isnull', True), ('km_arrivee__gte', models.F('km_depart')), _connector='OR'), name='mission_km_arrivee_apres_depart')],
            },
        ),
    ]
