# Generated by Django 5.2.17 on 2026-09-26 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('type_frais', models.CharField(choices=[('AVANCE_ROUTE', 'Avance de route'), ('DEPENSE_PREVUE', 'Dépense prévue'), ('IMPREVU', 'Imprévu (panne, incident)'), ('ENCAISSEMENT', 'Encaissement')], max_length=15, verbose_name='type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant (FCFA)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='libellé')),
                ('justificatif', models.FileField(blank=True, upload_to='frais_mission/justificatifs/%Y/%m/', verbose_name='justificatif')),
                ('statut', models.CharField(choices=[('PREVU', 'Prévu'), ('CONFIRME', 'Confirmé'), ('REJETE', 'Rejeté')], default='PREVU', max_length=10, verbose_name='statut')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='motif du rejet')),
                ('date_validation_parcauto', models.DateTimeField(blank=True, null=True, verbose_name='validé par le parc auto le')),
                ('date_validation_finances', models.DateTimeField(blank=True, null=True, verbose_name='validé par la finance le')),
                ('chauffeur', models.ForeignKey(blank=True, help_text="Renseigné pour un imprévu déclaré depuis l'espace mobile.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frais_mission_declares', to='drivers.chauffeur', verbose_name='chauffeur')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frais', to='missions.mission', verbose_name='mission')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='saisi par')),
                ('valide_finances_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validé par la finance')),
                ('valide_parcauto_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validé par le parc auto')),
            ],
            options={
                'verbose_name': 'frais de mission',
                'verbose_name_plural': 'frais de mission',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['mission', 'statut'], name='missions_fr_mission_ed328b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='frais_mission_montant_positif')],
            },
        ),
    ]
