# Generated by Django 5.2.17 on 2026-09-26 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_proforma'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='proforma',
            field=models.OneToOneField(blank=True, help_text='Devis accepté dont cette mission reprend le trajet et le prix (R6).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mission_creee', to='billing.proforma', verbose_name="devis d'origine"),
        ),
    ]
