# Generated by Django 5.2.17 on 2026-09-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_fraismission'),
        ('missions', '0002_mission_proforma'),
    ]

    operations = [
    ]
