# Generated by Django 5.2.17 on 2026-09-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_copilote'),
        ('missions', '0003_merge_0002_fraismission_0002_mission_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='copilote',
            field=models.ForeignKey(blank=True, help_text='Facultatif : certains voyages exigent un assistant au chauffeur.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='drivers.copilote', verbose_name='copilote'),
        ),
    ]
