# Generated by Django 5.2.17 on 2026-10-03 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_depense_montant_tva_alter_depense_montant_and_more'),
        ('missions', '0004_mission_copilote'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraismission',
            name='reglement',
            field=models.ForeignKey(blank=True, help_text="Renseigné pour un encaissement : le règlement qu'il reflète. Si ce règlement est annulé, l'encaissement disparaît de la prévision de trésorerie de la mission.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.reglement', verbose_name='règlement'),
        ),
    ]
