# Generated by Django 5.2.17 on 2026-09-19 11:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('poste', models.CharField(max_length=100, verbose_name='poste')),
                ('departement', models.CharField(choices=[('EXPLOITATION', 'Exploitation'), ('PARC_AUTO', 'Parc Auto'), ('COMPTABILITE', 'Comptabilité'), ('COMMERCIAL', 'Commercial'), ('DIRECTION', 'Direction')], max_length=20, verbose_name='département')),
                ('date_embauche', models.DateField(verbose_name="date d'embauche")),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='salaire de base (FCFA)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'personnel',
                'verbose_name_plural': 'personnel',
                'ordering': ['matricule'],
                'indexes': [models.Index(fields=['nom', 'prenom'], name='hr_personne_nom_638b03_idx')],
            },
        ),
    ]
