# Generated by Django 5.2.17 on 2026-09-19 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='est_chef_departement',
            field=models.BooleanField(default=False, help_text='Valide en N1 les congés des employés de son département.', verbose_name='chef de département'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='solde_conges_jours',
            field=models.PositiveIntegerField(default=0, verbose_name='solde de congés (jours)'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='type_contrat',
            field=models.CharField(blank=True, max_length=30, verbose_name='type de contrat'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to=settings.AUTH_USER_MODEL, verbose_name='compte utilisateur'),
        ),
    ]
