# Generated by Django 5.2.17 on 2026-09-19 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_personnel_contrat_solde_chef_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('date_debut', models.DateField(verbose_name='début')),
                ('date_fin', models.DateField(verbose_name='fin')),
                ('jours', models.PositiveIntegerField(verbose_name='jours décomptés')),
                ('motif', models.TextField(verbose_name='motif')),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demande'), ('VALIDATION_N1', 'Validé N1'), ('APPROUVE', 'Approuvé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('REFUSE', 'Refusé')], default='DEMANDE', max_length=15, verbose_name='statut')),
                ('date_limite_n1', models.DateTimeField(blank=True, null=True, verbose_name='échéance validation N1')),
                ('date_limite_n2', models.DateTimeField(blank=True, null=True, verbose_name='échéance validation N2')),
                ('motif_decision', models.TextField(blank=True, verbose_name="motif du refus / de l'annulation")),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges', to='hr.personnel', verbose_name='employé')),
            ],
            options={
                'verbose_name': 'congé',
                'verbose_name_plural': 'congés',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ValidationConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('niveau', models.PositiveSmallIntegerField(choices=[(1, 'N1 - chef de département'), (2, 'N2 - RH')], verbose_name='niveau')),
                ('decision', models.CharField(choices=[('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé')], max_length=10, verbose_name='décision')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('date_decision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de décision')),
                ('conge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations', to='hr.conge', verbose_name='congé')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('validateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validateur')),
            ],
            options={
                'verbose_name': 'validation de congé',
                'verbose_name_plural': 'validations de congé',
                'ordering': ['date_decision'],
            },
        ),
        migrations.AddIndex(
            model_name='conge',
            index=models.Index(fields=['statut', 'date_debut'], name='hr_conge_statut_069956_idx'),
        ),
        migrations.AddConstraint(
            model_name='conge',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='conge_fin_apres_debut'),
        ),
    ]
