# Generated by Django 5.2.17 on 2026-09-19 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_conges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='est_chef_departement',
        ),
        migrations.AddField(
            model_name='personnel',
            name='superieur',
            field=models.ForeignKey(blank=True, help_text='Valide en N1 les demandes de congé de cet employé.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordonnes', to='hr.personnel', verbose_name='supérieur hiérarchique'),
        ),
    ]
