# Generated by Django 5.2.17 on 2026-09-19 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_jours_feries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='solde_conges_jours',
        ),
        migrations.CreateModel(
            name='AttributionConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='année')),
                ('jours', models.PositiveIntegerField(verbose_name='jours accordés')),
                ('motif', models.TextField(verbose_name='motif')),
                ('accorde_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='accordé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributions_conges', to='hr.personnel', verbose_name='employé')),
            ],
            options={
                'verbose_name': 'attribution exceptionnelle de congé',
                'verbose_name_plural': 'attributions exceptionnelles de congé',
                'ordering': ['-annee', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('jours__gt', 0)), name='attribution_conge_jours_positifs')],
            },
        ),
    ]
