# Generated by Django 5.2.17 on 2026-09-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_droits_conges_annuels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationconge',
            name='niveau',
            field=models.PositiveSmallIntegerField(choices=[(1, 'N1 - supérieur hiérarchique'), (2, 'N2 - RH')], verbose_name='niveau'),
        ),
    ]
