# Generated by Django 5.2.17 on 2026-09-25 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_libelle_niveau_superieur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('nouvelle_date_fin', models.DateField(verbose_name='reprise du travail le')),
                ('jours_restants', models.PositiveIntegerField(verbose_name='jours restants reversés au solde')),
                ('motif', models.TextField(verbose_name='motif')),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demande'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé')], default='DEMANDE', max_length=10, verbose_name='statut')),
                ('motif_decision', models.TextField(blank=True, verbose_name='motif du refus')),
                ('date_decision', models.DateTimeField(blank=True, null=True, verbose_name='date de décision')),
                ('conge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='hr.conge', verbose_name='congé')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
            ],
            options={
                'verbose_name': 'report de congé',
                'verbose_name_plural': 'reports de congé',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('jours_restants__gt', 0)), name='report_conge_jours_positifs')],
            },
        ),
    ]
