# Generated by Django 5.2.17 on 2026-09-28 09:33

from django.db import migrations, models


def _reclasser_exploitation_vers_parc_auto(apps, schema_editor):
    """L'entreprise a confirmé que l'Exploitation ne forme pas un département à part : elle est
    gérée par le Parc Auto (cahier-des-charges.md:207). Aucune fiche existante ne doit rester sur
    l'ancien code une fois le choix retiré."""
    Personnel = apps.get_model("hr", "Personnel")
    # État historique de la migration : le manager n'est pas ``ActiveManager``/``all_objects``
    # (managers personnalisés non reportés sans ``use_in_migrations``) — ``objects`` couvre donc
    # déjà toutes les fiches, y compris soft-supprimées.
    Personnel.objects.filter(departement="EXPLOITATION").update(departement="PARC_AUTO")


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_report_conge'),
    ]

    operations = [
        migrations.RunPython(_reclasser_exploitation_vers_parc_auto, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='personnel',
            name='departement',
            field=models.CharField(choices=[('PARC_AUTO', 'Parc Auto'), ('COMPTABILITE', 'Comptabilité'), ('COMMERCIAL', 'Commercial'), ('DIRECTION', 'Direction')], max_length=20, verbose_name='département'),
        ),
    ]
