# Generated by Django 5.2.17 on 2026-09-28 10:05

from django.db import migrations, models


def _fusionner_comptabilite_dans_rh_finance(apps, schema_editor):
    """L'entreprise a confirmé que la RH n'a pas de département propre : elle est rattachée au
    même département que la Finance/Comptabilité (cahier-des-charges.md:207), renommé
    « Ressources Humaines et Finances ». Aucune fiche existante ne doit rester sur l'ancien code
    une fois le choix retiré."""
    Personnel = apps.get_model("hr", "Personnel")
    Personnel.objects.filter(departement="COMPTABILITE").update(departement="RH_FINANCE")


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_personnel_departement'),
    ]

    operations = [
        migrations.RunPython(_fusionner_comptabilite_dans_rh_finance, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='personnel',
            name='departement',
            field=models.CharField(choices=[('PARC_AUTO', 'Parc Auto'), ('RH_FINANCE', 'Ressources Humaines et Finances'), ('COMMERCIAL', 'Commercial'), ('DIRECTION', 'Direction')], max_length=20, verbose_name='département'),
        ),
    ]
