# Generated by Django 5.2.17 on 2026-09-26 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('hr', '0008_report_conge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Copilote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('contact_urgence', models.CharField(blank=True, max_length=150, verbose_name="contact d'urgence")),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_MISSION', 'En mission'), ('EN_CONGE', 'En congé'), ('SUSPENDU', 'Suspendu'), ('INACTIF', 'Inactif')], default='DISPONIBLE', max_length=12, verbose_name='statut')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('personnel', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='copilote', to='hr.personnel', verbose_name='personnel')),
            ],
            options={
                'verbose_name': 'copilote',
                'verbose_name_plural': 'copilotes',
                'ordering': ['personnel__matricule'],
            },
        ),
    ]
