# Generated by Django 5.2.17 on 2026-09-17 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date/heure')),
                ('utilisateur_nom', models.CharField(blank=True, max_length=150, verbose_name='nom utilisateur')),
                ('role', models.CharField(blank=True, max_length=20, verbose_name='rôle')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('VALIDATE', 'Validation')], max_length=10, verbose_name='action')),
                ('module', models.CharField(max_length=50, verbose_name='module')),
                ('entite', models.CharField(max_length=100, verbose_name='entité')),
                ('entite_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID entité')),
                ('ancienne_valeur', models.JSONField(blank=True, null=True, verbose_name='ancienne valeur')),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True, verbose_name='nouvelle valeur')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user-agent')),
                ('statut', models.CharField(choices=[('SUCCESS', 'Succès'), ('FAILED', 'Échec')], default='SUCCESS', max_length=10, verbose_name='statut')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "entrée d'audit",
                'verbose_name_plural': "journal d'audit",
                'db_table': 'audit_log',
                'ordering': ['-date_heure'],
                'indexes': [models.Index(fields=['module', 'entite', 'entite_id'], name='audit_log_module_998625_idx'), models.Index(fields=['utilisateur', 'date_heure'], name='audit_log_utilisa_6c7fbe_idx')],
            },
        ),
    ]
