# Generated by Django 5.2.17 on 2026-09-19 11:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('immatriculation', models.CharField(max_length=20, unique=True, verbose_name='immatriculation')),
                ('marque', models.CharField(max_length=50, verbose_name='marque')),
                ('modele', models.CharField(max_length=50, verbose_name='modèle')),
                ('annee', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1950)], verbose_name='année')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='n° de châssis (VIN)')),
                ('kilometrage', models.PositiveIntegerField(default=0, verbose_name='kilométrage compteur')),
                ('capacite_charge_t', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='capacité de charge (t)')),
                ('reservoir_l', models.PositiveIntegerField(verbose_name='réservoir (L)')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_MISSION', 'En mission'), ('EN_MAINTENANCE', 'En maintenance'), ('IMMOBILISE', 'Immobilisé'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=15, verbose_name='statut')),
                ('chauffeur_habituel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules_habituels', to='drivers.chauffeur', verbose_name='chauffeur habituel')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
            ],
            options={
                'verbose_name': 'véhicule',
                'verbose_name_plural': 'véhicules',
                'ordering': ['immatriculation'],
            },
        ),
        migrations.CreateModel(
            name='DocumentReglementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('type_document', models.CharField(choices=[('CARTE_GRISE', 'Carte grise'), ('ASSURANCE', 'Assurance'), ('VISITE_TECHNIQUE', 'Visite technique'), ('PATENTE', 'Patente')], max_length=20, verbose_name='type')),
                ('date_delivrance', models.DateField(verbose_name='date de délivrance')),
                ('date_expiration', models.DateField(verbose_name="date d'expiration")),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='fleet.vehicule', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'document réglementaire',
                'verbose_name_plural': 'documents réglementaires',
                'ordering': ['date_expiration'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['statut'], name='fleet_vehic_statut_168c32_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentreglementaire',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('vehicule', 'type_document'), name='document_unique_par_type_et_vehicule'),
        ),
        migrations.AddConstraint(
            model_name='documentreglementaire',
            constraint=models.CheckConstraint(condition=models.Q(('date_expiration__gte', models.F('date_delivrance'))), name='document_expiration_apres_delivrance'),
        ),
    ]
