# Generated by Django 5.2.17 on 2026-09-19 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('categorie', models.CharField(choices=[('CONGE', 'Congé'), ('STOCK', 'Stock'), ('CARBURANT', 'Carburant'), ('DOCUMENT', 'Échéance'), ('MISSION', 'Mission')], max_length=12, verbose_name='catégorie')),
                ('niveau', models.CharField(choices=[('INFO', 'Information'), ('ATTENTION', 'Attention'), ('URGENT', 'Urgent')], default='INFO', max_length=10, verbose_name='niveau')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='lien')),
                ('lue_le', models.DateTimeField(blank=True, null=True, verbose_name='lue le')),
                ('cle_unicite', models.CharField(blank=True, max_length=150, verbose_name="clé d'unicité")),
                ('email_envoye', models.BooleanField(default=False, verbose_name='e-mail envoyé')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='supprimé par')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['destinataire', 'lue_le'], name='notificatio_destina_112e9f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cle_unicite', ''), _negated=True), fields=('destinataire', 'cle_unicite'), name='notification_cle_unique_par_destinataire')],
            },
        ),
    ]
