# Generated by Django 5.2.17 on 2026-09-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_categorie_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='categorie',
            field=models.CharField(choices=[('CONGE', 'Congé'), ('STOCK', 'Stock'), ('CARBURANT', 'Carburant'), ('DOCUMENT', 'Échéance'), ('MISSION', 'Mission'), ('FACTURE', 'Facturation'), ('INCIDENT', 'Incident')], max_length=12, verbose_name='catégorie'),
        ),
    ]
