# Generated by Django 5.2.17 on 2026-09-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_categorie_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, help_text='Intitulé du bouton qui mène au lien (ex. « Confirmer le versement ») ; « Ouvrir » si vide.', max_length=60, verbose_name="bouton d'action"),
        ),
    ]
