# Generated by Django 5.2.17 on 2026-09-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_action_du_bouton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='categorie',
            field=models.CharField(choices=[('CONGE', 'Congé'), ('STOCK', 'Stock'), ('CARBURANT', 'Carburant'), ('DOCUMENT', 'Échéance'), ('MISSION', 'Mission'), ('FACTURE', 'Facturation'), ('PROFORMA', 'Devis'), ('FRAIS_MISSION', 'Frais de mission'), ('DEMANDE_DEPENSE', 'Demande de dépense'), ('INCIDENT', 'Incident')], max_length=15, verbose_name='catégorie'),
        ),
    ]
